function plot_path(x_path, y_path, color)
    path_elevation = 0.1;
    plot3(x_path, y_path, mountain_range(x_path, y_path) + path_elevation, strcat(color, '-'), 'LineWidth', 2); % Path line
    quiver3(...
        x_path(1:end-1), y_path(1:end-1), mountain_range(x_path(1:end-1), y_path(1:end-1)), ...
        x_path(2:end)-x_path(1:end-1), y_path(2:end)-y_path(1:end-1), ...
        mountain_range(x_path(2:end), y_path(2:end))-mountain_range(x_path(1:end-1), y_path(1:end-1)) + path_elevation, ...
        0.5, color, 'LineWidth', 1.5);
end
